# Generated by Django 5.1.3 on 2024-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=32)),
                ('ModelName', models.CharField(max_length=32)),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
