# Generated by Django 5.1.3 on 2024-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='CompanyName',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ModelName',
            field=models.CharField(max_length=23),
        ),
    ]
