# Generated by Django 5.1.3 on 2024-11-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0003_alter_laptop_companyname_alter_laptop_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='CompanyName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ModelName',
            field=models.CharField(max_length=32),
        ),
    ]
